//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.646.0 using the following command:
// xscgen --namespace=|Configuration.xsd=FinCleaner.Configuration.Schema --netCore Configuration.xsd
namespace FinCleaner.Configuration.Schema
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FilePattern", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilePattern
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("pattern")]
        public string Pattern { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("parser")]
        public string Parser { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ruleSet")]
        public string RuleSet { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Parser", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CsvParser))]
    public abstract partial class Parser
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CsvParser", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CsvParser : Parser
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Date")]
        public ValueSource Date { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public ValueSource Amount { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("AssetAccountName")]
        public ValueSource AssetAccountName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("AssetAccountIBAN")]
        public ValueSource AssetAccountIBAN { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("AssetAccountNumber")]
        public ValueSource AssetAccountNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("OppositeAccountName")]
        public ValueSource OppositeAccountName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("OppositeAccountIBAN")]
        public ValueSource OppositeAccountIBAN { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("OppositeAccountNumber")]
        public ValueSource OppositeAccountNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public ValueSource Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ValueSource Reference { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("encoding")]
        public FileEncoding Encoding { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("delimiter")]
        public string Delimiter { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("header")]
        public bool Header { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("culture")]
        public string Culture { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _quote = "\"";
        
        [System.ComponentModel.DefaultValueAttribute("\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("quote")]
        public string Quote
        {
            get
            {
                return this._quote;
            }
            set
            {
                this._quote = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CsvParserMode _mode = FinCleaner.Configuration.Schema.CsvParserMode.RFC4180;
        
        [System.ComponentModel.DefaultValueAttribute(FinCleaner.Configuration.Schema.CsvParserMode.RFC4180)]
        [System.Xml.Serialization.XmlAttributeAttribute("mode")]
        public CsvParserMode Mode
        {
            get
            {
                return this._mode;
            }
            set
            {
                this._mode = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ColumnValueSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileNameValueSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PatternValueSource))]
    public abstract partial class ValueSource
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FileEncoding", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    public enum FileEncoding
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("utf-8")]
        Utf_8,
        
        [System.Xml.Serialization.XmlEnumAttribute("utf-16")]
        Utf_16,
        
        [System.Xml.Serialization.XmlEnumAttribute("utf-16BE")]
        Utf_16BE,
        
        [System.Xml.Serialization.XmlEnumAttribute("ascii")]
        Ascii,
        
        [System.Xml.Serialization.XmlEnumAttribute("iso-8859-1")]
        Iso_8859_1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CsvParserMode", Namespace="http://schemas.org/fincleaner/configuration/1.0", AnonymousType=true)]
    public enum CsvParserMode
    {
        
        Escape,
        
        NoEscape,
        
        RFC4180,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ColumnValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ColumnValueSource : ValueSource
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("columnIndex")]
        public int ColumnIndex { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FileNameValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileNameValueSource : ValueSource
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PatternValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PatternValueSource : ValueSource
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public ValueSource Source { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PatternValue> _value;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public System.Collections.ObjectModel.Collection<PatternValue> Value
        {
            get
            {
                return this._value;
            }
            private set
            {
                this._value = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PatternValueSource" /> class.</para>
        /// </summary>
        public PatternValueSource()
        {
            this._value = new System.Collections.ObjectModel.Collection<PatternValue>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PatternValue", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FixedPatternValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MatchedPatternValue))]
    public abstract partial class PatternValue
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("pattern")]
        public string Pattern { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FixedPatternValue", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FixedPatternValue : PatternValue
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MatchedPatternValue", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatchedPatternValue : PatternValue
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MatchedPatternValueReplace> _replace;
        
        [System.Xml.Serialization.XmlElementAttribute("Replace")]
        public System.Collections.ObjectModel.Collection<MatchedPatternValueReplace> Replace
        {
            get
            {
                return this._replace;
            }
            private set
            {
                this._replace = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Replace collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceSpecified
        {
            get
            {
                return (this.Replace.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MatchedPatternValue" /> class.</para>
        /// </summary>
        public MatchedPatternValue()
        {
            this._replace = new System.Collections.ObjectModel.Collection<MatchedPatternValueReplace>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("groupName")]
        public string GroupName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("trim")]
        public bool Trim { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Trim property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrimSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MatchedPatternValueReplace", Namespace="http://schemas.org/fincleaner/configuration/1.0", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatchedPatternValueReplace
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("pattern")]
        public string Pattern { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RuleSet", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RuleSet
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Rule> _rule;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Rule")]
        public System.Collections.ObjectModel.Collection<Rule> Rule
        {
            get
            {
                return this._rule;
            }
            private set
            {
                this._rule = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RuleSet" /> class.</para>
        /// </summary>
        public RuleSet()
        {
            this._rule = new System.Collections.ObjectModel.Collection<Rule>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Rule", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterRule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModifyFieldsRule))]
    public abstract partial class Rule
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TransactionCondition> _condition;
        
        [System.Xml.Serialization.XmlElementAttribute("Condition")]
        public System.Collections.ObjectModel.Collection<TransactionCondition> Condition
        {
            get
            {
                return this._condition;
            }
            private set
            {
                this._condition = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Condition collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConditionSpecified
        {
            get
            {
                return (this.Condition.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Rule" /> class.</para>
        /// </summary>
        public Rule()
        {
            this._condition = new System.Collections.ObjectModel.Collection<TransactionCondition>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ConditionMatchingMode _conditionMatchingMode = FinCleaner.Configuration.Schema.ConditionMatchingMode.All;
        
        [System.ComponentModel.DefaultValueAttribute(FinCleaner.Configuration.Schema.ConditionMatchingMode.All)]
        [System.Xml.Serialization.XmlAttributeAttribute("conditionMatchingMode")]
        public ConditionMatchingMode ConditionMatchingMode
        {
            get
            {
                return this._conditionMatchingMode;
            }
            set
            {
                this._conditionMatchingMode = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TransactionCondition", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AmountRangeCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldTransactionCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeywordCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MissingValueCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PatternCondition))]
    public abstract partial class TransactionCondition
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConditionMatchingMode", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    public enum ConditionMatchingMode
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("all")]
        All,
        
        [System.Xml.Serialization.XmlEnumAttribute("any")]
        Any,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ModifyFieldsRule", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyFieldsRule : Rule
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Date")]
        public TransactionValueSource Date { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public TransactionValueSource Amount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AssetAccountName")]
        public TransactionValueSource AssetAccountName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AssetAccountIBAN")]
        public TransactionValueSource AssetAccountIBAN { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AssetAccountNumber")]
        public TransactionValueSource AssetAccountNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OppositeAccountName")]
        public TransactionValueSource OppositeAccountName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OppositeAccountIBAN")]
        public TransactionValueSource OppositeAccountIBAN { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OppositeAccountNumber")]
        public TransactionValueSource OppositeAccountNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public TransactionValueSource Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public TransactionValueSource Reference { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TransactionValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldTransactionValueSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FixedTransactionValueSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NullTransactionValueSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReplaceTransactionValueSource))]
    public abstract partial class TransactionValueSource
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FilterRule", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterRule : Rule
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AmountRangeCondition", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AmountRangeCondition : TransactionCondition
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("min")]
        public int Min { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Min property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _minInclusive = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("minInclusive")]
        public bool MinInclusive
        {
            get
            {
                return this._minInclusive;
            }
            set
            {
                this._minInclusive = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("max")]
        public int Max { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Max property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _maxInclusive = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("maxInclusive")]
        public bool MaxInclusive
        {
            get
            {
                return this._maxInclusive;
            }
            set
            {
                this._maxInclusive = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FieldTransactionCondition", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeywordCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MissingValueCondition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PatternCondition))]
    public abstract partial class FieldTransactionCondition : TransactionCondition
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("field")]
        public TransactionField Field { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TransactionField", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    public enum TransactionField
    {
        
        AssetAccountName,
        
        AssetAccountIBAN,
        
        AssetAccountNumber,
        
        OppositeAccountName,
        
        OppositeAccountIBAN,
        
        OppositeAccountNumber,
        
        Description,
        
        Reference,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PatternCondition", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PatternCondition : FieldTransactionCondition
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("pattern")]
        public string Pattern { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _ignoreCase = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("ignoreCase")]
        public bool IgnoreCase
        {
            get
            {
                return this._ignoreCase;
            }
            set
            {
                this._ignoreCase = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KeywordCondition", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KeywordCondition : FieldTransactionCondition
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("keyword")]
        public string Keyword { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MissingValueCondition", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MissingValueCondition : FieldTransactionCondition
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NullTransactionValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NullTransactionValueSource : TransactionValueSource
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FixedTransactionValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FixedTransactionValueSource : TransactionValueSource
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FieldTransactionValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FieldTransactionValueSource : TransactionValueSource
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("field")]
        public TransactionField Field { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReplaceTransactionValueSource", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReplaceTransactionValueSource : TransactionValueSource
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public TransactionValueSource Source { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("pattern")]
        public string Pattern { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _ignoreCase = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("ignoreCase")]
        public bool IgnoreCase
        {
            get
            {
                return this._ignoreCase;
            }
            set
            {
                this._ignoreCase = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("replacement")]
        public string Replacement { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Configuration", Namespace="http://schemas.org/fincleaner/configuration/1.0", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Configuration", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
    public partial class Configuration
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Settings")]
        public ConfigurationSettings Settings { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("FilePatterns")]
        public ConfigurationFilePatterns FilePatterns { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Parser> _fileParsers;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("FileParsers")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parser", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
        public System.Collections.ObjectModel.Collection<Parser> FileParsers
        {
            get
            {
                return this._fileParsers;
            }
            private set
            {
                this._fileParsers = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Configuration" /> class.</para>
        /// </summary>
        public Configuration()
        {
            this._fileParsers = new System.Collections.ObjectModel.Collection<Parser>();
            this._ruleSets = new System.Collections.ObjectModel.Collection<RuleSet>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RuleSet> _ruleSets;
        
        [System.Xml.Serialization.XmlArrayAttribute("RuleSets")]
        [System.Xml.Serialization.XmlArrayItemAttribute("RuleSet", Namespace="http://schemas.org/fincleaner/configuration/1.0")]
        public System.Collections.ObjectModel.Collection<RuleSet> RuleSets
        {
            get
            {
                return this._ruleSets;
            }
            private set
            {
                this._ruleSets = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the RuleSets collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RuleSetsSpecified
        {
            get
            {
                return (this.RuleSets.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConfigurationSettings", Namespace="http://schemas.org/fincleaner/configuration/1.0", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfigurationSettings
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ExportCulture")]
        public string ExportCulture { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("FallbackAccountName")]
        public string FallbackAccountName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("FallbackAccountIBAN")]
        public string FallbackAccountIBAN { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("FallbackAccountNumber")]
        public string FallbackAccountNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("FallbackDescription")]
        public string FallbackDescription { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConfigurationFilePatterns", Namespace="http://schemas.org/fincleaner/configuration/1.0", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfigurationFilePatterns
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FilePattern> _pattern;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Pattern")]
        public System.Collections.ObjectModel.Collection<FilePattern> Pattern
        {
            get
            {
                return this._pattern;
            }
            private set
            {
                this._pattern = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConfigurationFilePatterns" /> class.</para>
        /// </summary>
        public ConfigurationFilePatterns()
        {
            this._pattern = new System.Collections.ObjectModel.Collection<FilePattern>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("defaultParser")]
        public string DefaultParser { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("defaultRuleSet")]
        public string DefaultRuleSet { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConfigurationFileParsers", Namespace="http://schemas.org/fincleaner/configuration/1.0", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfigurationFileParsers
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Parser> _parser;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Parser")]
        public System.Collections.ObjectModel.Collection<Parser> Parser
        {
            get
            {
                return this._parser;
            }
            private set
            {
                this._parser = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConfigurationFileParsers" /> class.</para>
        /// </summary>
        public ConfigurationFileParsers()
        {
            this._parser = new System.Collections.ObjectModel.Collection<Parser>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.646.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConfigurationRuleSets", Namespace="http://schemas.org/fincleaner/configuration/1.0", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfigurationRuleSets
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RuleSet> _ruleSet;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("RuleSet")]
        public System.Collections.ObjectModel.Collection<RuleSet> RuleSet
        {
            get
            {
                return this._ruleSet;
            }
            private set
            {
                this._ruleSet = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConfigurationRuleSets" /> class.</para>
        /// </summary>
        public ConfigurationRuleSets()
        {
            this._ruleSet = new System.Collections.ObjectModel.Collection<RuleSet>();
        }
    }
}
